apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-k8-courses
data:
  port: "8002"
  db_host: postgres-container:5432
  database: msvc-k8-courses
  #username: postgres
  #password: sasa
  users_url: msvc-k8-users:8001
  environment: prod
  msvc-k8-courses.yaml: |-
    config:
      texto: Configurando ambiente por defecto
    ---
    spring:
      config:
        activate:
          on-profile: dev
    config:
      texto: Configurando ambiente de Desarrollo
    ---
    spring:
      config:
        activate:
          on-profile: prod
    config:
      texto: Configurando ambiente de Produccion