apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-k8-courses
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-k8-courses
  template:
    metadata:
      labels:
        app: msvc-k8-courses
    spec:
      containers:
      - image: luisenriquesm/msvc-k8-courses:v1
        name: msvc-k8-courses
        ports:
        - containerPort: 8002
        env:
          - name: PORT
            value: "8002"
          - name: DB_HOST
            value: postgres-container:5432
          - name: DB_DATABASE
            value: msvc-k8-courses
          - name: DB_USERNAME
            value: postgres
          - name: DB_PASSWORD
            value: sasa
          - name: USERS_URL
            value: msvc-k8-users:8001