apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres14
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres14
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: sasa
            - name: POSTGRES_DB
              value: msvc-k8-courses
          volumeMounts:
            - name: data-postgres
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data-postgres
          persistentVolumeClaim:
            claimName: postgres-pvc
