apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-k8-courses
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-k8-courses
  template:
    metadata:
      labels:
        app: msvc-k8-courses
    spec:
      containers:
      - image: luisenriquesm/msvc-k8-courses:v1
        name: msvc-k8-courses
        ports:
        - containerPort: 8002
        env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: msvc-k8-courses
                key: port
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: msvc-k8-courses
                key: db_host
          - name: DB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: msvc-k8-courses
                key: database
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: msvc-k8-courses
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: msvc-k8-courses
                key: password
          - name: USERS_URL
            valueFrom:
              configMapKeyRef:
                name: msvc-k8-courses
                key: users_url