apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-k8-users
spec:
  replicas: 2
  selector:
    matchLabels:
      app: msvc-k8-users
  template:
    metadata:
      labels:
        app: msvc-k8-users
    spec:
      containers:
      - image: luisenriquesm/msvc-k8-users:v5
        imagePullPolicy: Always
        name: msvc-k8-users
        ports:
        - containerPort: 8001
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: msvc-k8-users
                key: port
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: msvc-k8-users
                key: db_host
          - name: DB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: msvc-k8-users
                key: database
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: msvc-k8-users
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: msvc-k8-users
                key: password
          - name: COURSES_URL
            valueFrom:
              configMapKeyRef:
                name: msvc-k8-users
                key: courses_url
          - name: ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: msvc-k8-users
                key: environment
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8001
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8001
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "400Mi"
            cpu: "350m"

