apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
#  storageClassName: standard
  storageClassName: ""
  accessModes:
#    - ReadWriteOnce
    - ReadWriteMany
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-054dda91d837f4d83
  # hostPath:
  #   path: /var/lib/postgresql/data
  #   type: DirectoryOrCreate